/**
 * MidOcean category_level1/category_level2/category_level3 -> TGV leaf map.
 *
 * Snapshot source: products API 2.0, English, 2026-08-15.
 * Coverage: 240 normalized taxonomy tuples across 15,290 variants.
 *
 * MidOcean publishes the taxonomy on each variant. All three levels are part
 * of the key, including an empty level 3. This is deliberately fail-closed:
 * a new supplier tuple must be reviewed before it can enter the catalogue.
 */

export interface MidoceanCategoryInput {
  categoryLevel1: string
  categoryLevel2: string
  categoryLevel3?: string
}
const CATEGORY_KEY_SEPARATOR = "\u001f"

export function normalizeMidoceanCategoryPart(value: string): string {
  return value.normalize("NFKC").trim().replaceAll(/\s+/g, " ").toLocaleLowerCase("en")
}

export function midoceanCategoryKey(
  categoryLevel1: string,
  categoryLevel2: string,
  categoryLevel3 = "",
): string {
  return [categoryLevel1, categoryLevel2, categoryLevel3]
    .map(normalizeMidoceanCategoryPart)
    .join(CATEGORY_KEY_SEPARATOR)
}

export const MIDOCEAN_CATEGORY_MAP: Readonly<Record<string, string>> = Object.freeze({
  "bags & travel\u001fbackpacks\u001fanti-theft backpacks": "bags/backpacks/anti-theft-backpacks",
  "bags & travel\u001fbackpacks\u001fbackpacks": "bags/backpacks/standard-backpacks",
  "bags & travel\u001fbackpacks\u001flaptop backpacks": "bags/backpacks/laptop-backpacks",
  "bags & travel\u001fbackpacks\u001freflective bags": "bags/backpacks/standard-backpacks",
  "bags & travel\u001fbusiness bags\u001fdocument bags": "bags/specialty-bags/document-and-laptop-bags",
  "bags & travel\u001fbusiness bags\u001flaptop bags": "bags/specialty-bags/document-and-laptop-bags",
  "bags & travel\u001fbusiness bags\u001flaptop sleeves": "bags/specialty-bags/document-and-laptop-bags",
  "bags & travel\u001fdrawstring bags\u001f": "bags/backpacks/drawstring-bags",
  "bags & travel\u001fgift bags\u001fgift bags": "bags/gift-bags",
  "bags & travel\u001fgift bags\u001fpaper bags": "bags/gift-bags",
  "bags & travel\u001fshopping bags\u001ffoldable bags": "bags/shopping-bags/foldable-bags",
  "bags & travel\u001fshopping bags\u001ffood bags": "bags/shopping-bags/rpet-and-recycled-bags",
  "bags & travel\u001fshopping bags\u001flarge shopping bags": "bags/shopping-bags/cotton-and-canvas",
  "bags & travel\u001fshopping bags\u001ftote bags": "bags/shopping-bags/cotton-and-canvas",
  "bags & travel\u001fsports & outdoor bags\u001fbeach bags": "bags/shopping-bags/cotton-and-canvas",
  "bags & travel\u001fsports & outdoor bags\u001fcooler bags": "bags/specialty-bags/cooler-bags",
  "bags & travel\u001fsports & outdoor bags\u001fsports & gym bags": "bags/specialty-bags/gym-and-sports-bags",
  "bags & travel\u001fsports & outdoor bags\u001fwaist & cross body bags": "bags/specialty-bags/fanny-packs-and-waist-bags",
  "bags & travel\u001fsports & outdoor bags\u001fwaterproof bags": "bags/specialty-bags/waterproof-bags",
  "bags & travel\u001ftravel accessories\u001f": "accommodation-and-travel/travel-accessories",
  "bags & travel\u001ftravel accessories\u001fadapters skross": "electronics/power-and-charging/charging-cables-and-adapters",
  "bags & travel\u001ftravel accessories\u001fblankets & cushions": "home-and-living/textiles/blankets",
  "bags & travel\u001ftravel accessories\u001fluggage tags": "accommodation-and-travel/travel-accessories",
  "bags & travel\u001ftravel accessories\u001ftoiletry bags": "accommodation-and-travel/toiletry-bags",
  "bags & travel\u001ftravel accessories\u001ftravel accessories": "accommodation-and-travel/travel-accessories",
  "bags & travel\u001ftravel accessories\u001fwallets & rfid": "accommodation-and-travel/travel-accessories",
  "bags & travel\u001fweekend bags & trolleys\u001fcarry on trolleys": "accommodation-and-travel/travel-bags-and-luggage",
  "bags & travel\u001fweekend bags & trolleys\u001fweekend bags": "accommodation-and-travel/travel-bags-and-luggage",
  "clothing & wearables\u001fbrands\u001fsol's": "apparel-and-wearables/sportswear-and-activewear",
  "clothing & wearables\u001fchristmas jumpers\u001f": "apparel-and-wearables/seasonal-wearables",
  "clothing & wearables\u001ffleece & softshell\u001ffleece": "apparel-and-wearables/sweaters-and-fleece",
  "clothing & wearables\u001ffleece & softshell\u001fsoftshell": "apparel-and-wearables/jackets-and-bodywarmers",
  "clothing & wearables\u001fkids\u001f": "apparel-and-wearables/sportswear-and-activewear",
  "clothing & wearables\u001foccasion to wear\u001fsports & active wear": "apparel-and-wearables/sportswear-and-activewear",
  "clothing & wearables\u001fouterwear\u001fbodywarmers": "apparel-and-wearables/jackets-and-bodywarmers",
  "clothing & wearables\u001fouterwear\u001fjackets": "apparel-and-wearables/jackets-and-bodywarmers",
  "clothing & wearables\u001fouterwear\u001fparkas": "apparel-and-wearables/jackets-and-bodywarmers",
  "clothing & wearables\u001fouterwear\u001fwindbreakers": "apparel-and-wearables/jackets-and-bodywarmers",
  "clothing & wearables\u001fpolo shirts\u001f": "apparel-and-wearables/polo-shirts",
  "clothing & wearables\u001fpolo shirts\u001flong sleeves": "apparel-and-wearables/polo-shirts",
  "clothing & wearables\u001fpolo shirts\u001fshort sleeves": "apparel-and-wearables/polo-shirts",
  "clothing & wearables\u001fshirts\u001f": "apparel-and-wearables/fashion-apparel/shirts",
  "clothing & wearables\u001fsweaters\u001f": "apparel-and-wearables/sweaters-and-fleece",
  "clothing & wearables\u001fsweatshirts\u001fcrew neck": "apparel-and-wearables/sweaters-and-fleece",
  "clothing & wearables\u001fsweatshirts\u001ffull zip": "apparel-and-wearables/sweaters-and-fleece",
  "clothing & wearables\u001fsweatshirts\u001fhalf zip": "apparel-and-wearables/sweaters-and-fleece",
  "clothing & wearables\u001fsweatshirts\u001fhoodie": "apparel-and-wearables/sweaters-and-fleece",
  "clothing & wearables\u001ft-shirts\u001f": "apparel-and-wearables/t-shirts",
  "clothing & wearables\u001ft-shirts\u001flong sleeves": "apparel-and-wearables/t-shirts",
  "clothing & wearables\u001ft-shirts\u001fshort sleeves": "apparel-and-wearables/t-shirts",
  "clothing & wearables\u001ftextile categories\u001ft-shirts": "apparel-and-wearables/t-shirts",
  "drink & lunchware\u001fbottles\u001fdouble wall bottles": "drinkware/bottles/thermal-and-vacuum-flasks",
  "drink & lunchware\u001fbottles\u001fglass bottles": "drinkware/bottles/water-bottles",
  "drink & lunchware\u001fbottles\u001fhip flasks": "drinkware/bottles/hip-flasks",
  "drink & lunchware\u001fbottles\u001fsmart bottles & sets": "drinkware/bottles/water-bottles",
  "drink & lunchware\u001fbottles\u001fvacuum flasks": "drinkware/bottles/thermal-and-vacuum-flasks",
  "drink & lunchware\u001fbottles\u001fwater & sports bottles": "drinkware/bottles/sport-bottles",
  "drink & lunchware\u001fceramics\u001fmugs": "drinkware/mugs-and-cups/ceramic-mugs",
  "drink & lunchware\u001fceramics\u001fsets": "drinkware/mugs-and-cups/ceramic-mugs",
  "drink & lunchware\u001fglasses hospitality\u001fcarafes": "drinkware/mugs-and-cups/glass-mugs",
  "drink & lunchware\u001fglasses hospitality\u001flong glasses": "drinkware/mugs-and-cups/glass-mugs",
  "drink & lunchware\u001fglasses hospitality\u001fsets": "drinkware/mugs-and-cups/glass-mugs",
  "drink & lunchware\u001fglasses hospitality\u001fshort glasses": "drinkware/mugs-and-cups/glass-mugs",
  "drink & lunchware\u001fglasses hospitality\u001fshot glasses": "drinkware/mugs-and-cups/glass-mugs",
  "drink & lunchware\u001fglasses hospitality\u001ftea & coffee glasses": "drinkware/mugs-and-cups/glass-mugs",
  "drink & lunchware\u001fglasses hospitality\u001fwine glasses": "drinkware/mugs-and-cups/glass-mugs",
  "drink & lunchware\u001flunchware\u001fcutlery": "home-and-living/kitchen-and-dining/kitchen-tools-and-utensils",
  "drink & lunchware\u001flunchware\u001flunch boxes": "home-and-living/kitchen-and-dining/lunch-boxes-and-food-containers",
  "drink & lunchware\u001flunchware\u001fstraws": "drinkware/bar-and-wine-accessories/reusable-straws",
  "drink & lunchware\u001fmugs & tumblers\u001fmugs & cups": "drinkware/mugs-and-cups/ceramic-mugs",
  "drink & lunchware\u001fmugs & tumblers\u001ftumblers double wall": "drinkware/mugs-and-cups/travel-tumblers",
  "drink & lunchware\u001fmugs & tumblers\u001ftumblers single wall": "drinkware/mugs-and-cups/travel-tumblers",
  "head & multiwear\u001fbeanies\u001fbeanies": "apparel-and-wearables/headwear/beanies",
  "head & multiwear\u001fcaps & hats\u001fbaseball caps 5 panels": "apparel-and-wearables/headwear/caps-and-hats",
  "head & multiwear\u001fcaps & hats\u001fbaseball caps 6 panels": "apparel-and-wearables/headwear/caps-and-hats",
  "head & multiwear\u001fcaps & hats\u001fbucket hats": "apparel-and-wearables/headwear/caps-and-hats",
  "head & multiwear\u001fcaps & hats\u001fflat visors": "apparel-and-wearables/headwear/visors",
  "head & multiwear\u001fcaps & hats\u001fhats": "apparel-and-wearables/headwear/caps-and-hats",
  "head & multiwear\u001fcaps & hats\u001fperformance caps": "apparel-and-wearables/headwear/caps-and-hats",
  "head & multiwear\u001fcaps & hats\u001ftrucker caps": "apparel-and-wearables/headwear/caps-and-hats",
  "head & multiwear\u001ffootwear\u001fslippers & sliders": "apparel-and-wearables/seasonal-wearables",
  "head & multiwear\u001ffootwear\u001fsneakers": "apparel-and-wearables/seasonal-wearables",
  "head & multiwear\u001ffootwear\u001fsocks": "apparel-and-wearables/socks",
  "head & multiwear\u001fmultiscarves\u001fheadbands": "apparel-and-wearables/textile-accessories",
  "head & multiwear\u001fmultiscarves\u001fmultiscarves": "apparel-and-wearables/textile-accessories",
  "head & multiwear\u001fscarves & gloves\u001fgloves": "apparel-and-wearables/textile-accessories",
  "head & multiwear\u001fscarves & gloves\u001fscarves": "apparel-and-wearables/textile-accessories",
  "home & wellness\u001fcandles & fragrances\u001fcandles": "home-and-living/home-decor/candles-and-fragrances",
  "home & wellness\u001fcandles & fragrances\u001fdiffusers & scents": "home-and-living/home-decor/candles-and-fragrances",
  "home & wellness\u001fcosmetics\u001flipbalms": "home-and-living/personal-care-and-wellness/lip-balms",
  "home & wellness\u001fcosmetics\u001fsun lotions": "home-and-living/personal-care-and-wellness/sun-care",
  "home & wellness\u001fmints & sweets\u001f": "seasonal-gifts",
  "home & wellness\u001fpersonal care\u001fbath accessories": "home-and-living/seasonal-and-event-items/household-accessories",
  "home & wellness\u001fpersonal care\u001fcare essentials": "home-and-living/seasonal-and-event-items/household-accessories",
  "home & wellness\u001fpersonal care\u001fheat & cold pads": "home-and-living/seasonal-and-event-items/household-accessories",
  "home & wellness\u001fpersonal care\u001fmirrors": "home-and-living/personal-care-and-wellness/mirrors",
  "home & wellness\u001fpersonal care\u001fnail kits": "home-and-living/personal-care-and-wellness/nail-and-manicure-kits",
  "home & wellness\u001fpersonal care\u001fsoaps & gels": "home-and-living/personal-care-and-wellness/hand-sanitizers-and-gels",
  "home & wellness\u001fpersonal care\u001ftoiletry & cosmetic bags": "accommodation-and-travel/toiletry-bags",
  "home & wellness\u001ftowels & blankets\u001fblankets": "home-and-living/textiles/blankets",
  "kids & games\u001fbaby & toddlers\u001f": "kids-and-games/baby-and-toddler-products",
  "kids & games\u001findoor games\u001fanti stress": "kids-and-games/toys-and-plush/outdoor-and-indoor-games",
  "kids & games\u001findoor games\u001fbrain teasers": "kids-and-games/toys-and-plush/outdoor-and-indoor-games",
  "kids & games\u001findoor games\u001fcard games": "kids-and-games/toys-and-plush/outdoor-and-indoor-games",
  "kids & games\u001findoor games\u001fdesk games": "kids-and-games/toys-and-plush/outdoor-and-indoor-games",
  "kids & games\u001findoor games\u001fothers": "kids-and-games/toys-and-plush/outdoor-and-indoor-games",
  "kids & games\u001foutdoor games\u001f": "kids-and-games/toys-and-plush/outdoor-and-indoor-games",
  "kids & games\u001foutdoor games\u001finflatables": "kids-and-games/toys-and-plush/outdoor-and-indoor-games",
  "kids & games\u001foutdoor games\u001foutdoor games": "kids-and-games/toys-and-plush/outdoor-and-indoor-games",
  "kids & games\u001fstuffed animals\u001f": "kids-and-games/toys-and-plush/stuffed-animals",
  "kids & games\u001fwriting & colouring\u001fart paints": "kids-and-games/creative-play/drawing-and-coloring-items",
  "kids & games\u001fwriting & colouring\u001fcolouring pencils": "kids-and-games/creative-play/drawing-and-coloring-items",
  "kids & games\u001fwriting & colouring\u001fcolouring sets": "kids-and-games/creative-play/drawing-and-coloring-items",
  "kids & games\u001fwriting & colouring\u001fkids colouring bags": "kids-and-games/creative-play/drawing-and-coloring-items",
  "kids & games\u001fwriting & colouring\u001fpencil cases & accessories": "kids-and-games/creative-play/pencil-cases-and-accessories",
  "kitchen & accessories\u001fgift sets\u001fcheese sets": "home-and-living/kitchen-and-dining/cutting-boards",
  "kitchen & accessories\u001fgift sets\u001fcocktail sets & accessories": "drinkware/bar-and-wine-accessories/cocktail-sets",
  "kitchen & accessories\u001fgift sets\u001fwine sets & accessories": "drinkware/bar-and-wine-accessories/wine-sets",
  "kitchen & accessories\u001fhome & hospitality textiles\u001faprons & gloves": "home-and-living/kitchen-and-dining/aprons-and-gloves",
  "kitchen & accessories\u001fhome & hospitality textiles\u001fkitchen & table linen": "home-and-living/kitchen-and-dining/aprons-and-gloves",
  "kitchen & accessories\u001fhome & hospitality textiles\u001fothers": "home-and-living/textiles/towels",
  "kitchen & accessories\u001fkitchenware\u001fboards": "home-and-living/kitchen-and-dining/cutting-boards",
  "kitchen & accessories\u001fkitchenware\u001fbottle openers & stoppers": "drinkware/bar-and-wine-accessories/bottle-openers-and-stoppers",
  "kitchen & accessories\u001fkitchenware\u001fchef ́s knives": "home-and-living/kitchen-and-dining/kitchen-tools-and-utensils",
  "kitchen & accessories\u001fkitchenware\u001fcoasters": "drinkware/bar-and-wine-accessories/coasters",
  "kitchen & accessories\u001fkitchenware\u001fkitchen utensils": "home-and-living/kitchen-and-dining/kitchen-tools-and-utensils",
  "kitchen & accessories\u001fkitchenware\u001fothers": "home-and-living/kitchen-and-dining/kitchen-tools-and-utensils",
  "kitchen & accessories\u001ftea & coffee\u001f": "home-and-living/kitchen-and-dining/kitchen-tools-and-utensils",
  "lanyards & events\u001fbadges & holders\u001f": "lanyards-and-events/badges-and-holders",
  "lanyards & events\u001flanyards\u001fbadge reels lanyards": "lanyards-and-events/lanyards",
  "lanyards & events\u001flanyards\u001fcord lanyards": "lanyards-and-events/lanyards",
  "lanyards & events\u001flanyards\u001fsilk screen lanyards": "lanyards-and-events/lanyards",
  "lanyards & events\u001flanyards\u001fspecial lanyards": "lanyards-and-events/lanyards",
  "lanyards & events\u001flanyards\u001fwrist & phone holders": "lanyards-and-events/lanyards",
  "lanyards & events\u001fpins & buttons\u001fbuttons": "lanyards-and-events/pins-and-buttons",
  "lanyards & events\u001fsunglasses\u001f": "outdoor-and-leisure/travel-and-beach/sunglasses",
  "lanyards & events\u001fsunglasses\u001fcleaning cloths & cases": "outdoor-and-leisure/travel-and-beach/sunglasses",
  "lanyards & events\u001fwristbands\u001f": "lanyards-and-events/wristbands",
  "office & writing\u001fcomputer accessories\u001fhubs": "electronics/power-and-charging/charging-cables-and-adapters",
  "office & writing\u001fcomputer accessories\u001fphone stands & holders": "electronics/computer-and-mobile-accessories/phone-holders-and-stands",
  "office & writing\u001fdesk accessories\u001fdesk & wall clocks": "home-and-living/home-decor/clocks-and-weather-stations",
  "office & writing\u001fdesk accessories\u001fdesk lamps": "office-and-writing/office-accessories/desk-accessories",
  "office & writing\u001fdesk accessories\u001fmousepads & mouses": "electronics/computer-and-mobile-accessories/computer-mice-and-mousepads",
  "office & writing\u001fdesk accessories\u001fothers": "office-and-writing/office-accessories/desk-accessories",
  "office & writing\u001fdesk accessories\u001ftrophies (awards) & paper weights": "office-and-writing/office-accessories/trophies-and-paperweights",
  "office & writing\u001fdesk accessories\u001fweather stations": "home-and-living/home-decor/clocks-and-weather-stations",
  "office & writing\u001fnotebooks\u001fcombi sets": "office-and-writing/notebooks-and-planners/notebooks",
  "office & writing\u001fnotebooks\u001fhard cover": "office-and-writing/notebooks-and-planners/notebooks",
  "office & writing\u001fnotebooks\u001fringbound (spiral)": "office-and-writing/notebooks-and-planners/notebooks",
  "office & writing\u001fnotebooks\u001fsoft cover": "office-and-writing/notebooks-and-planners/notebooks",
  "office & writing\u001fpaper desk accessories\u001fdesk pads & calendars": "office-and-writing/notebooks-and-planners/diaries-and-almanacs",
  "office & writing\u001fpaper desk accessories\u001fmemo pads & sticky notes": "office-and-writing/notebooks-and-planners/notebooks",
  "office & writing\u001fphone accessories\u001fothers": "electronics/computer-and-mobile-accessories/phone-holders-and-stands",
  "office & writing\u001fportfolios\u001fconference folders": "office-and-writing/office-accessories/folders-and-portfolios",
  "office & writing\u001fportfolios\u001fsmart folders": "office-and-writing/office-accessories/folders-and-portfolios",
  "office & writing\u001fwriting\u001faccessories & cases": "office-and-writing/writing-instruments/gift-sets",
  "office & writing\u001fwriting\u001fball pens": "office-and-writing/writing-instruments/ball-pens",
  "office & writing\u001fwriting\u001fgift writing sets": "office-and-writing/writing-instruments/gift-sets",
  "office & writing\u001fwriting\u001fhighlighters": "office-and-writing/writing-instruments/highlighters",
  "office & writing\u001fwriting\u001finkless pens": "office-and-writing/writing-instruments/ball-pens",
  "office & writing\u001fwriting\u001fmultifunctional pens": "office-and-writing/writing-instruments/stylus-pens",
  "office & writing\u001fwriting\u001fpencils": "office-and-writing/writing-instruments/pencils",
  "office & writing\u001fwriting\u001fstylus pens": "office-and-writing/writing-instruments/stylus-pens",
  "outdoor & leisure\u001fbarbecue\u001f": "outdoor-and-leisure/outdoor-gear/barbecue-and-picnic-items",
  "outdoor & leisure\u001fbeach items\u001fbeach & hammam towels": "outdoor-and-leisure/sports-and-fitness/sports-towels",
  "outdoor & leisure\u001fbeach items\u001fbeach games": "outdoor-and-leisure/travel-and-beach/beach-items",
  "outdoor & leisure\u001fgardening\u001fgardening tools": "outdoor-and-leisure/outdoor-gear/gardening-tools",
  "outdoor & leisure\u001fgardening\u001fplants & seed items": "outdoor-and-leisure/outdoor-gear/gardening-tools",
  "outdoor & leisure\u001fhammocks & chairs\u001f": "outdoor-and-leisure/outdoor-gear/camping-gear",
  "outdoor & leisure\u001foutdoor events\u001fhand fans": "lanyards-and-events/event-accessories/fans",
  "outdoor & leisure\u001foutdoor events\u001fseat mats": "outdoor-and-leisure/outdoor-gear/barbecue-and-picnic-items",
  "outdoor & leisure\u001fpicnic & camping\u001f": "outdoor-and-leisure/outdoor-gear/camping-gear",
  "outdoor & leisure\u001fsport & health\u001fbicycle accessories": "outdoor-and-leisure/sports-and-fitness/cycling-accessories",
  "outdoor & leisure\u001fsport & health\u001ffitness & yoga accessories": "outdoor-and-leisure/sports-and-fitness/fitness-and-yoga-accessories",
  "outdoor & leisure\u001fsport & health\u001ffootball items": "outdoor-and-leisure/sports-and-fitness/football-items",
  "outdoor & leisure\u001fsport & health\u001fmedals": "office-and-writing/office-accessories/trophies-and-paperweights",
  "outdoor & leisure\u001fsport & health\u001fmultiscarves": "apparel-and-wearables/textile-accessories",
  "outdoor & leisure\u001fsport & health\u001freflectives": "apparel-and-wearables/workwear-and-safety",
  "outdoor & leisure\u001fsport & health\u001frunning & hiking accessories": "outdoor-and-leisure/sports-and-fitness/running-and-hiking-accessories",
  "outdoor & leisure\u001fsport & health\u001fsmartphone pouches": "bags/specialty-bags/fanny-packs-and-waist-bags",
  "outdoor & leisure\u001fsport & health\u001fsports towels": "outdoor-and-leisure/sports-and-fitness/sports-towels",
  "outdoor & leisure\u001fsunglasses\u001fsunglasses": "outdoor-and-leisure/travel-and-beach/sunglasses",
  "seasonal gifts\u001fcandles & lights\u001f": "home-and-living/home-decor/candles-and-fragrances",
  "seasonal gifts\u001fcatalogues\u001f": "office-and-writing/office-accessories/folders-and-portfolios",
  "seasonal gifts\u001fdecoration\u001f": "home-and-living/seasonal-and-event-items/christmas-decorations",
  "seasonal gifts\u001fdrink & lunchware\u001f": "seasonal-gifts",
  "seasonal gifts\u001fothers\u001f": "seasonal-gifts",
  "seasonal gifts\u001fwearables\u001f": "apparel-and-wearables/seasonal-wearables",
  "technology\u001faa/aaa batteries\u001f": "electronics/usb-flash-drives",
  "technology\u001fphone accessories\u001fcables": "electronics/power-and-charging/charging-cables-and-adapters",
  "technology\u001fphone accessories\u001fothers": "electronics/computer-and-mobile-accessories/phone-holders-and-stands",
  "technology\u001fphone accessories\u001fphone cords & straps": "electronics/computer-and-mobile-accessories/phone-holders-and-stands",
  "technology\u001fphone accessories\u001ftablet & phone stands": "electronics/computer-and-mobile-accessories/phone-holders-and-stands",
  "technology\u001fpower banks\u001fhigh capacity ≥8.000": "electronics/power-and-charging/power-banks",
  "technology\u001fpower banks\u001flow capacity ≥2.000": "electronics/power-and-charging/power-banks",
  "technology\u001fpower banks\u001fmid capacity ≥4.000": "electronics/power-and-charging/power-banks",
  "technology\u001fpower banks\u001fmultifunctional": "electronics/power-and-charging/power-banks",
  "technology\u001fpower banks\u001fpowerbank with wireless charging": "electronics/power-and-charging/power-banks",
  "technology\u001fpower banks\u001fsolar": "electronics/power-and-charging/power-banks",
  "technology\u001fsmart finders\u001f": "electronics/smart-devices/smart-finders",
  "technology\u001fsmartwatches\u001f": "electronics/smart-devices/smartwatches",
  "technology\u001fspeakers & earphones\u001fearphones": "electronics/audio-devices/earphones-and-headphones",
  "technology\u001fspeakers & earphones\u001fheadphones": "electronics/audio-devices/earphones-and-headphones",
  "technology\u001fspeakers & earphones\u001fmultifunctional speakers": "electronics/audio-devices/bluetooth-speakers",
  "technology\u001fspeakers & earphones\u001fspeakers": "electronics/audio-devices/bluetooth-speakers",
  "technology\u001fusb flashdrives\u001f": "electronics/usb-flash-drives",
  "technology\u001fwireless chargers\u001fcar chargers": "electronics/power-and-charging/wireless-chargers",
  "technology\u001fwireless chargers\u001fmagnetic chargers": "electronics/power-and-charging/wireless-chargers",
  "technology\u001fwireless chargers\u001fmultifunctional chargers": "electronics/power-and-charging/wireless-chargers",
  "technology\u001fwireless chargers\u001fsets": "electronics/power-and-charging/wireless-chargers",
  "technology\u001fwireless chargers\u001fwireless chargers": "electronics/power-and-charging/wireless-chargers",
  "tools & keyrings\u001fcar accessories\u001fcar air freshners": "tools-and-keyrings/car-accessories/car-air-fresheners",
  "tools & keyrings\u001fcar accessories\u001fcar blankets": "tools-and-keyrings/car-accessories/fire-and-emergency-blankets",
  "tools & keyrings\u001fcar accessories\u001fcar phone holders & chargers": "tools-and-keyrings/car-accessories/car-phone-holders",
  "tools & keyrings\u001fcar accessories\u001fice scrapers": "tools-and-keyrings/car-accessories/ice-scrapers",
  "tools & keyrings\u001fcar accessories\u001fothers": "tools-and-keyrings/car-accessories/car-organizers-and-accessories",
  "tools & keyrings\u001fcar accessories\u001fsafety car tools": "tools-and-keyrings/tools/multi-tools",
  "tools & keyrings\u001fcar accessories\u001fsunshades": "tools-and-keyrings/car-accessories/car-sunshades",
  "tools & keyrings\u001fkeyrings\u001fbasic keyrings": "tools-and-keyrings/keyrings/basic-keyrings",
  "tools & keyrings\u001fkeyrings\u001ffabric keyrings": "tools-and-keyrings/keyrings/basic-keyrings",
  "tools & keyrings\u001fkeyrings\u001fmultifunctional keyrings": "tools-and-keyrings/keyrings/multifunctional-keyrings",
  "tools & keyrings\u001fkeyrings\u001fopener keyrings": "tools-and-keyrings/keyrings/multifunctional-keyrings",
  "tools & keyrings\u001fkeyrings\u001freflective keyrings": "tools-and-keyrings/keyrings/basic-keyrings",
  "tools & keyrings\u001fkeyrings\u001fsmart key finders and alarms": "tools-and-keyrings/keyrings/smart-key-finders",
  "tools & keyrings\u001fkeyrings\u001ftoken keyrings": "tools-and-keyrings/keyrings/basic-keyrings",
  "tools & keyrings\u001fkeyrings\u001ftorch keyrings": "tools-and-keyrings/keyrings/multifunctional-keyrings",
  "tools & keyrings\u001freflective items\u001freflective items": "apparel-and-wearables/workwear-and-safety",
  "tools & keyrings\u001freflective items\u001fsafety vests": "apparel-and-wearables/workwear-and-safety",
  "tools & keyrings\u001ftools & torches\u001fdynamo & solar torches": "tools-and-keyrings/tools/flashlights-and-torches",
  "tools & keyrings\u001ftools & torches\u001fmeasuring tapes": "tools-and-keyrings/tools/measuring-tapes",
  "tools & keyrings\u001ftools & torches\u001fmulti tools": "tools-and-keyrings/tools/multi-tools",
  "tools & keyrings\u001ftools & torches\u001fpocket knives": "tools-and-keyrings/tools/pocket-knives",
  "tools & keyrings\u001ftools & torches\u001ftool sets & other tools": "tools-and-keyrings/tools/multi-tools",
  "tools & keyrings\u001ftools & torches\u001ftorches": "tools-and-keyrings/tools/flashlights-and-torches",
  "umbrellas & rainwear\u001frainwear\u001fponchos": "umbrellas-and-rainwear/rainwear/raincoats",
  "umbrellas & rainwear\u001frainwear\u001fraincoats": "umbrellas-and-rainwear/rainwear/raincoats",
  "umbrellas & rainwear\u001fumbrellas\u001ffoldable umbrellas": "umbrellas-and-rainwear/umbrellas/folding-umbrellas",
  "umbrellas & rainwear\u001fumbrellas\u001fregular umbrellas": "umbrellas-and-rainwear/umbrellas/standard-umbrellas",
  "umbrellas & rainwear\u001fumbrellas\u001fsun umbrellas": "umbrellas-and-rainwear/umbrellas/golf-umbrellas",
  "umbrellas & rainwear\u001fumbrellas\u001fwindproof umbrellas": "umbrellas-and-rainwear/umbrellas/golf-umbrellas",
})

/** Lower-camel alias for adapters that prefer value-style imports. */
export const midoceanCategoryMap = MIDOCEAN_CATEGORY_MAP

export function mapMidoceanCategory(input: MidoceanCategoryInput): string
export function mapMidoceanCategory(
  categoryLevel1: string,
  categoryLevel2: string,
  categoryLevel3?: string,
): string
export function mapMidoceanCategory(
  inputOrCategoryLevel1: MidoceanCategoryInput | string,
  categoryLevel2?: string,
  categoryLevel3 = "",
): string {
  const input = typeof inputOrCategoryLevel1 === "string"
    ? {
        categoryLevel1: inputOrCategoryLevel1,
        categoryLevel2: categoryLevel2 ?? "",
        categoryLevel3,
      }
    : inputOrCategoryLevel1

  const key = midoceanCategoryKey(
    input.categoryLevel1,
    input.categoryLevel2,
    input.categoryLevel3 ?? "",
  )
  const mapped = MIDOCEAN_CATEGORY_MAP[key]
  if (mapped) return mapped

  throw new Error(
    `Unknown MidOcean category tuple: ${JSON.stringify({
      categoryLevel1: input.categoryLevel1,
      categoryLevel2: input.categoryLevel2,
      categoryLevel3: input.categoryLevel3 ?? "",
    })}`,
  )
}
