/**
 * Column names published by the XD Connects V5 combined data feed.
 *
 * Values intentionally remain strings. Conversion belongs in the adapter so
 * that the transport layer can preserve the supplier's source data exactly.
 */
export const XDCONNECTS_V5_HEADERS = [
  "FeedCreatedDateTime",
  "ItemPrintDataLastModifiedDateTime",
  "ItemPrintPriceLastModifiedDateTime",
  "Currency",
  "ModelCode",
  "ItemCode",
  "ProductLifeCycle",
  "IntroDate",
  "ItemName",
  "LongDescription",
  "Brand",
  "MainCategory",
  "SubCategory",
  "Material",
  "Color",
  "PMSColor1",
  "PMSColor2",
  "HexColor1",
  "HexColor2",
  "InkColor",
  "ItemLengthCM",
  "ItemWidthCM",
  "ItemHeightCM",
  "ItemDiameterCM",
  "ItemDimensions",
  "ItemWeightNetGr",
  "ItemWeightGrossGr",
  "CountryOfOrigin",
  "CommodityCode",
  "EANCode",
  "WEEE",
  "Batteries",
  "BatteryType",
  "NrOfBatteries",
  "BatteryWeightGr",
  "BatteryChemicalComposition",
  "IECCode",
  "ItemManual",
  "PackagingTypeItem",
  "ItemBoxLengthCM",
  "ItemBoxWidthCM",
  "ItemBoxHeightCM",
  "ItemBoxDiameterCM",
  "ItemBoxDimensions",
  "OuterCartonLengthCM",
  "OuterCartonWidthCM",
  "OuterCartonHeightCM",
  "OuterCartonDimensions",
  "OuterCartonWeightNetKG",
  "OuterCartonWeightGrossKG",
  "InnerboxQty",
  "OuterCartonQty",
  "RestrictedCountriesForSale",
  "Mailable",
  "Compliance",
  "Certifications",
  "DangerousGoods",
  "Social Audits",
  "Eco",
  "Traceability",
  "Charity",
  "Used PET Bottles",
  "PVC free",
  "Recycled Content Percent",
  "Digital passport",
  "HasFSCPackaging",
  "HasPlasticFreePackaging",
  "Product Box net weight plastic GR",
  "Product Box net weight carton GR",
  "Product Box net weight other GR",
  "Product Box gross weight GR",
  "Dishwasher safe",
  "Carry handle",
  "CarryHandleType",
  "HasANC",
  "ANCLevelDB",
  "HasAutoPair",
  "ChargingCaseBatteryCapacityMAh",
  "EarbudBatteryCapacityMAh",
  "BTVersion",
  "InputChargingConnectorType",
  "ChargingTimeHours",
  "HasENC",
  "ExtraEarTipsIncluded",
  "IsFoldable",
  "HasPouch",
  "ChargingCableIncluded",
  "HasIntegratedLight",
  "HasMicrophone",
  "OperatingDistanceMeters",
  "AudioWearMethod",
  "HasPickupFunction",
  "PlayTimeHours",
  "HasSubwoofer",
  "HasTouchFunction",
  "HasUSBOutput",
  "HasVoiceControl",
  "HasBluetooth",
  "NumberOfSpeakers",
  "SpeakerOutputW",
  "WaterproofLevel",
  "HasChestStrap",
  "FitsLaptopTabletSizeInches",
  "MaximumSupportedCurrent",
  "SupportsCarPlay",
  "HasLightningOutput",
  "HasMicroUSBOutput",
  "ChargingCableLengthCM",
  "CanCableSync",
  "IsMicrowaveSafe",
  "Leak Prevention",
  "Insulation",
  "HoursHot",
  "HoursCold",
  "FitsCoffeeMachine",
  "ContentVolumeLiters",
  "CircumferenceCM",
  "HatClosureType",
  "HatModel",
  "USBVersion",
  "USBAPortQty",
  "USBCPortQty",
  "LaserClass",
  "BookCoverType",
  "NotebookFormat",
  "PaperWeight",
  "StationaryPaperColor",
  "NumberOfPages",
  "PaperRulingLayout",
  "USBAChargingOutputSpeed",
  "USBCChargingOutputSpeed",
  "PhoneChargeCount",
  "HasUSBCOutput",
  "CanChargeTablet",
  "CanChargeLaptop",
  "TotalOutputPowerWatt",
  "HasWirelessChargingInput",
  "HasPassThroughCharging",
  "HasMagneticWirelessChargingOutput",
  "IsAirlineCarryOnApproved",
  "ChargeSimultaneousDevices",
  "ChargingIndicator",
  "HasFastCharging",
  "ChargingPowerWatt",
  "WirelessCharging",
  "PowerbankCapacity",
  "HasSolarPanel",
  "SolarInputPower",
  "HasUV400Filter",
  "HasPolarizedGlasses",
  "SunglassCategory",
  "TextileSize",
  "TextileStyle",
  "Care Instruction",
  "Sleeve Length",
  "Neckline",
  "Fit",
  "Fabric Grams per m2",
  "Fabric",
  "Has neck label",
  "Has Tear-away label",
  "Undyed",
  "MeasuringTapeColor",
  "HasAutoStop",
  "HasMagnet",
  "HasSlowRetractFunction",
  "TapeWidthMM",
  "NumberOfFunctions",
  "IsMeasuringTapeDoubleSided",
  "MeasuringSystem",
  "BeamDistanceMeters",
  "NumberOfLightModes",
  "OperatingTimeHours",
  "IsRechargable",
  "Lumen",
  "TapeLengthMeters",
  "LightSource",
  "LightSourceQty",
  "CanopyDiameterCM",
  "UmbrellaMechanism",
  "IsStormProof",
  "InputSpeedVoltAmpere",
  "NumberOfWirelessChargingCoils",
  "PenMechanism",
  "PenRefillType",
  "Total CO2 emissions",
  "Total CO2 emissions benchmark",
  "M2F CO2 emissions KG",
  "M2F CO2 benchmark KG",
  "M2F CO2 saving Percent",
  "M2F water usage M3",
  "M2F water benchmark M3",
  "M2F water saving Percent",
  "M2F land usage M2",
  "M2F land benchmark M2",
  "M2F land usage saving Percent",
  "LCA Total CO2 Kg emissions",
  "LCA Total CO2 Kg emissions benchmark",
  "LCA CO2 Gr Material and Production",
  "LCA CO2 Gr Packaging",
  "LCA CO2 Gr Transport",
  "LCA CO2 Gr Electronics and Energy",
  "LCA CO2 Gr EOL",
  "LCA CO2 Percent Material and Production",
  "LCA CO2 Percent Packaging",
  "LCA CO2 Percent Transport",
  "LCA CO2 Percent Electronics and energy",
  "LCA CO2 Percent EOL",
  "AllImages",
  "MainImage",
  "MainImage Neutral",
  "ExtraImage1",
  "ExtraImage2",
  "ExtraImage3",
  "ExtraImage4",
  "ExtraImage5",
  "ExtraImage6",
  "ExtraImage7",
  "ImagePrint",
  "ImageGroupBlank",
  "ImageGroupPrint",
  "ImageMood1",
  "ImageMood2",
  "ImageMood3",
  "VideoURLVimeo",
  "VideoURLYoutube",
  "AllPrintCodes",
  "PrintCodeDefault",
  "PrintTechniqueDefault",
  "PrintPositionDefault",
  "MaxPrintWidthDefaultMM",
  "MaxPrintHeightDefaultMM",
  "MaxPrintAreaDefault",
  "MaxColorsDefault",
  "FullColorDefault",
  "LineDrawingDefault",
  "VariableDataPrinting",
  "CustomSleevePossible",
  "GiftWrappingPossible",
  "NonStandardDiscount",
  "Outlet",
  "Qty1",
  "Qty2",
  "Qty3",
  "Qty4",
  "Qty5",
  "Qty6",
  "ItemPriceNet_Qty1",
  "ItemPriceNet_Qty2",
  "ItemPriceNet_Qty3",
  "ItemPriceNet_Qty4",
  "ItemPriceNet_Qty5",
  "ItemPriceNet_Qty6",
  "ItemPriceGross_Qty1",
  "ItemPriceGross_Qty2",
  "ItemPriceGross_Qty3",
  "ItemPriceGross_Qty4",
  "ItemPriceGross_Qty5",
  "ItemPriceGross_Qty6",
  "PrintPriceDefaultNet_Qty1",
  "PrintPriceDefaultNet_Qty2",
  "PrintPriceDefaultNet_Qty3",
  "PrintPriceDefaultNet_Qty4",
  "PrintPriceDefaultNet_Qty5",
  "PrintPriceDefaultNet_Qty6",
  "PrintPriceDefaultGross_Qty1",
  "PrintPriceDefaultGross_Qty2",
  "PrintPriceDefaultGross_Qty3",
  "PrintPriceDefaultGross_Qty4",
  "PrintPriceDefaultGross_Qty5",
  "PrintPriceDefaultGross_Qty6",
  "AllinPriceNet_Qty1",
  "AllinPriceNet_Qty2",
  "AllinPriceNet_Qty3",
  "AllinPriceNet_Qty4",
  "AllinPriceNet_Qty5",
  "AllinPriceNet_Qty6",
  "AllinPriceGross_Qty1",
  "AllinPriceGross_Qty2",
  "AllinPriceGross_Qty3",
  "AllinPriceGross_Qty4",
  "AllinPriceGross_Qty5",
  "AllinPriceGross_Qty6",
  "SetupNet",
  "PrintSampleNet",
  "SmallOrderChargeNet",
  "MOQBlankOrder",
  "MOQPrintOrder",
  "CurrentStock",
  "FutureIncomingStockDate1",
  "FutureIncomingStockQty1",
] as const

export type XdConnectsKnownHeader = (typeof XDCONNECTS_V5_HEADERS)[number]

/** A source row keyed by supplier header, including any future unknown columns. */
export type XdConnectsRow = {
  [Header in XdConnectsKnownHeader]: string
} & Record<string, string>

export interface XdConnectsParsedFeed {
  headers: string[]
  rows: XdConnectsRow[]
  feedCreatedDateTime: string
  currency: string
}

export interface XdConnectsFeed extends XdConnectsParsedFeed {
  /** Normalized supplier FeedCreatedDateTime, used as the data-freshness time. */
  fetchedAt: string
  fromCache: boolean
}

export interface XdConnectsCacheMetadata {
  version: 1
  fetchedAt: string
  fetchedAtMs: number
  rawFile: string
  sha256: string
  byteLength: number
  rowCount: number
  feedCreatedDateTime: string
  currency: string
}
